=== fedihanna/cSharp/Assingment_4/FediLogger/logger.dtd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by wo (ke) --><!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><!ELEMENT Handlers (LogEventHandler*)><!ELEMENT LogEventHandler (property?)><!ATTLIST LogEventHandler	id (default | secs) #REQUIRED	class CDATA #IMPLIED><!ELEMENT LogLevel (LogEventHandler+)><!ATTLIST LogLevel	id (0 | 1 | 2 | 3 | 4 | 5) #REQUIRED	name (V_ALL | V_DEBUG | V_ERROR | V_FATAL | V_INFO | V_WARN) #REQUIRED><!ELEMENT LogLevels (LogLevel+)><!ATTLIST LogLevels	max CDATA #REQUIRED><!ELEMENT LoggerProfile (Version, Handlers, LogLevels)><!ELEMENT Version EMPTY><!ATTLIST Version	major CDATA #REQUIRED	minor CDATA #REQUIRED	build CDATA #REQUIRED><!ELEMENT property (#PCDATA)><!ATTLIST property	id CDATA #REQUIRED	type CDATA #REQUIRED>

=== fedihanna/cSharp/Assingment_4/Logger/logger.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE LoggerProfile SYSTEM "F:\My Development\SECSTalk\Logger\Logger\logger.dtd"><LoggerProfile>	<Version major="1" minor="0" build="0"/>	<Handlers>		<LogEventHandler id="default" class="BasicFileLogEventHandler">			<property id="filename" type="int">output.txt</property>		</LogEventHandler>		<LogEventHandler id="secs" class="BasicFileLogEventHandler">			<property id="filename" type="int">secs.txt</property>		</LogEventHandler>	</Handlers>	<LogLevels max="6">		<LogLevel id="0" name="V_FATAL">			<LogEventHandler id="default"/>			<LogEventHandler id="secs"/>		</LogLevel>		<LogLevel id="1" name="V_ERROR">			<LogEventHandler id="default"/>		</LogLevel>		<LogLevel id="2" name="V_WARN">			<LogEventHandler id="default"/>		</LogLevel>		<LogLevel id="3" name="V_INFO">			<LogEventHandler id="default"/>		</LogLevel>		<LogLevel id="4" name="V_DEBUG">			<LogEventHandler id="default"/>		</LogLevel>		<LogLevel id="5" name="V_ALL">			<LogEventHandler id="default"/>		</LogLevel>	</LogLevels></LoggerProfile>
